apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: ai-platform
spec:
  template:
    spec:
      volumes:
        - name: minio-data
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
