apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ai-platform
spec:
  template:
    spec:
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: ai-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
